# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:
 - mongo:3.5.6
#  - redis:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - backend/node_modules/

stages:
  - backend

backend-test:
  stage: backend
  coverage: '/^Statements[\s]*:[\s]*(\d+\.*\d*%)/'
  script:
   - cd backend
   - export NODE_ENV=test
   - npm install
   - npm run coverage
  artifacts:
    paths:
     - coverage
   
backend-lint:
  stage: backend
  script:
   - cd backend
   - export NODE_ENV=test
   - npm install
   - npm run lint
