env:
  node: true
  mocha: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
plugins:
  - security
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  valid-jsdoc:
    - error
  require-jsdoc: 1
  prefer-const:
    - error
  no-console: 0

