env:
  node: true
  mocha: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
  ecmaVersion: 2017
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  valid-jsdoc:
    - error
  require-jsdoc: 1
  prefer-const:
    - error
  no-console: warn
  no-redeclare: error
  no-self-assign: error
  no-useless-return: error
  no-unused-vars: error
  callback-return: error
  brace-style:
   - error
   - 1tbs
  capitalized-comments: error
  comma-dangle: error
  comma-spacing: error
  comma-style:
   - error
   - last
  consistent-this:
   - error
   - self